name: Build Pipeline

on:
  pull_request:
    branches:
      - production
  push:
    branches:
      - production

jobs:
  build-windows:
    runs-on: windows-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          submodules: recursive

      - name: Setup CMake and necessary tools
        run: |
          choco install cmake

      - name: Set up Visual Studio
        uses: microsoft/setup-msbuild@v1.1
        with:
          vs-version: "latest"

      - name: Clear CMake build directories
        run: |
          if (Test-Path Build) {
            Remove-Item Build -Recurse -Force
          }

      - name: Configure CMake
        run: |
          cmake -B Build -D CMAKE_BUILD_TYPE=Release -D CMAKE_GENERATOR_PLATFORM=x64

      - name: Build
        run: cmake --build Build --config Release

      - name: Prepare build artifacts
        run: |
          mkdir build-Windows
          Move-Item Build/*_artefacts/Release/VST3/*.vst3 build-Windows/

      - name: Archive build artifacts
        uses: actions/upload-artifact@v3
        with:
          name: build-Windows
          path: build-Windows/

  build-macos:
    runs-on: macos-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          submodules: recursive

      - name: Install dependencies
        run: |
          brew install cmake

      - name: Set up Xcode
        uses: actions/setup-node@v2
        with:
          node-version: "20"

      - name: Clear CMake build directories
        run: |
          if [ -d Build ]; then
            rm -rf Build
          fi

      - name: Configure CMake
        run: cmake -B Build -D CMAKE_BUILD_TYPE=Release

      - name: Build
        run: cmake --build Build --config Release

      - name: Prepare build artifacts
        run: |
          mkdir build-macOS
          mv Build/*_artefacts/Release/VST3/*.vst3 build-macOS/

      - name: Archive build artifacts
        uses: actions/upload-artifact@v3
        with:
          name: build-macOS
          path: build-macOS/